# jawl-machine-setup
:toc: auto

command, tool, package

## 0. setup machine 
.first time only
....
pkg upgrade
....
// pkg search
// termux-change-repo

##  1. install packages 

### `git` package

first check that `git` exist
....
git
....

it should show something like this:
====
----
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [--super-prefix=<path>] [--config-env=<name>=<envvar>]
           <command> [<args>]
----
====

if not exist, then install using `pkg` command
....
pkg install git
....

### `gh`
.check if `gh` exist, install if not
....
gh
....
....
pkg install gh
....

### `ssh` 
.check if exist, install if not
....
ssh
pkg install openssh
....

### generate keys
....
ssh-keygen 
ssh-keygen -t ed25519 -C"<email>"
ssh-add .ssh/id_ed25519
cat .ssh/id_ed25519  # private key
cat .ssh/id_ed25519.pub 
....

### show checksums [info]
....
cd .ssh/
md5 id_ed25519
sha256sum id_ed25519
sha256sum id_ed25519.pub 
sha1sum id_ed25519*
md5sum id*
....

## repository

### clone
----
gh repo clone jawl
cd jawl
----

### `git` config user
.first time on machine
....
git config --global user.email <email>
git config --global user.name <name>
....


### create `setup.history` file
....
cd jawl                     # goes into jawl directory
history                     # show command history
history > setup.history     # puts ^this^ history to a file
git add setup.history       # adds file to git 
git commit -m"history!"     # commits this file
git push
....